# Generated by Django 5.1.5 on 2025-02-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='Category_Name',
        ),
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ManyToManyField(default=1, related_name='event', to='events.event'),
        ),
    ]
