# Generated by Django 5.1.5 on 2025-02-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='event_asset/default-img.jpg', null=True, upload_to='event_asset'),
        ),
    ]
